import React, { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import api from '../../api/client'
import { Card, Badge, Spinner, Button, Modal, PageHeader, SectionDivider } from '../../components/common/index.jsx'
import Invoice from '../../components/common/Invoice.jsx'

export function PatientBilling() {
  const [selectedBill, setSelectedBill] = useState(null)

  const { data: bills = [], isLoading } = useQuery({
    queryKey: ['my-bills'],
    queryFn: () => api.get('/billing/').then(r => r.data),
  })

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      <PageHeader title="My Invoices" subtitle="View and download your medical bills" />

      {isLoading ? (
        <div style={{ display: 'flex', justifyContent: 'center', padding: 80 }}><Spinner /></div>
      ) : bills.length === 0 ? (
        <Card>
          <div style={{ textAlign: 'center', padding: '40px 0', color: 'var(--text-dim)' }}>
            <div style={{ fontSize: 48, marginBottom: 16 }}>🧾</div>
            <div style={{ fontWeight: 600 }}>No bills found</div>
            <p style={{ fontSize: 13, marginTop: 8 }}>Your invoices will appear here once generated by the hospital.</p>
          </div>
        </Card>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 20 }}>
          {bills.map(bill => (
            <Card key={bill.id}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-dim)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Bill Date</div>
                  <div style={{ fontWeight: 700, fontSize: 15 }}>{new Date(bill.billed_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
                </div>
                <Badge status={bill.payment_status} />
              </div>

              <div style={{ background: 'var(--navy-2)', padding: '16px', borderRadius: 12, marginBottom: 20 }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', textTransform: 'uppercase', marginBottom: 4 }}>Amount Due</div>
                <div style={{ fontSize: 24, fontWeight: 800, color: 'var(--blue)' }}>₹{parseFloat(bill.total_amount).toLocaleString('en-IN')}</div>
              </div>

              <div style={{ display: 'flex', gap: 12 }}>
                <Button variant="brand" style={{ flex: 1 }} onClick={() => setSelectedBill(bill)}>View Invoice</Button>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Invoice Modal */}
      <Modal open={!!selectedBill} onClose={() => setSelectedBill(null)} width={800} title="My Invoice">
        {selectedBill && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 20 }}>
              <Button onClick={() => window.print()} icon="print">Print / Save PDF</Button>
            </div>
            <Invoice bill={selectedBill} />
          </div>
        )}
      </Modal>
    </div>
  )
}
